import { StyleSheet } from 'react-native';
import { colors, radius } from '../theme';
import { insuranceFonts, insurancePalette } from './insurance/InsurancePanelPrimitives';

export default StyleSheet.create({
  selectedDocumentCard: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: radius.medium,
    padding: 14,
    marginBottom: 14,
  },
  selectedDocumentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  selectedDocumentIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedDocumentCopy: {
    flex: 1,
  },
  selectedDocumentTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 4,
  },
  selectedDocumentMeta: {
    color: colors.mutedText,
    fontSize: 12,
    lineHeight: 18,
  },
  selectedDocumentActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  checklistHeading: {
    color: colors.labelText,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.4,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  checklistGroup: {
    gap: 8,
    marginBottom: 14,
  },
  checklistRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  checklistIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checklistIconWrapComplete: {
    borderColor: colors.primaryGlow,
    backgroundColor: colors.primarySoft,
  },
  checklistRowText: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
    flex: 1,
  },
  checklistRowTextComplete: {
    color: colors.primary,
    fontWeight: '700',
  },
  checklistHelperText: {
    color: colors.mutedText,
    fontSize: 12,
    lineHeight: 18,
  },
  documentTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  documentTypeChip: {
    minHeight: 40,
    paddingHorizontal: 12,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  documentTypeChipSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  documentTypeChipText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  documentTypeChipTextSelected: {
    color: colors.primary,
  },
  statePanel: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    borderRadius: radius.large,
    padding: 16,
    marginBottom: 14,
  },
  statePanelDanger: {
    borderColor: 'rgba(255, 107, 107, 0.4)',
  },
  statePanelWarning: {
    borderColor: 'rgba(234, 179, 8, 0.35)',
  },
  statePanelSuccess: {
    borderColor: 'rgba(63, 215, 143, 0.35)',
  },
  statePanelHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  statePanelIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  statePanelCopy: {
    flex: 1,
  },
  statePanelTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  statePanelText: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
  },
  statePanelButton: {
    alignSelf: 'flex-start',
    marginTop: 14,
    minHeight: 40,
    paddingHorizontal: 14,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statePanelButtonText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  timelineStepList: {
    gap: 10,
  },
  timelineStepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 2,
  },
  timelineStepRail: {
    alignItems: 'center',
    paddingTop: 4,
  },
  timelineStepDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  timelineStepDotDone: {
    borderColor: colors.primaryGlow,
    backgroundColor: colors.primary,
  },
  timelineStepDotCurrent: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  timelineStepCopy: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: radius.medium,
    padding: 12,
  },
  timelineStepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 6,
  },
  timelineStepTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
    flex: 1,
  },
  timelineStepText: {
    color: colors.mutedText,
    fontSize: 12,
    lineHeight: 18,
  },
  timelineStepMeta: {
    color: colors.labelText,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 8,
  },
  timelineCard: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    borderRadius: radius.large,
    padding: 16,
    marginBottom: 14,
  },
  timelineCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 12,
  },
  timelineCardCopy: {
    flex: 1,
  },
  timelineCardTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  timelineCardSubtitle: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primaryGlow,
  },
  statusBadgeText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  detailRow: {
    marginTop: 8,
  },
  detailRowLabel: {
    color: colors.labelText,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 2,
    textTransform: 'uppercase',
  },
  detailRowValue: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
  },
  statusSectionEyebrow: {
    color: insurancePalette.amber,
    fontFamily: insuranceFonts.body,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  statusSectionTitle: {
    color: insurancePalette.text,
    fontFamily: insuranceFonts.heading,
    fontSize: 18,
    fontWeight: '700',
  },
  statusSectionSubtitle: {
    color: insurancePalette.textMuted,
    fontFamily: insuranceFonts.body,
    fontSize: 14,
    lineHeight: 22,
  },
  statusSectionMeta: {
    color: insurancePalette.textDim,
    fontFamily: insuranceFonts.body,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  statusHistoryList: {
    marginTop: 2,
  },
  statusHistoryRow: {
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: insurancePalette.divider,
    gap: 4,
  },
  statusHistoryLabel: {
    color: insurancePalette.text,
    fontFamily: insuranceFonts.heading,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  statusHistorySummary: {
    color: insurancePalette.textMuted,
    fontFamily: insuranceFonts.body,
    fontSize: 13,
    lineHeight: 20,
  },
  statusHistoryEmpty: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
  },
})
