import { StyleSheet } from 'react-native';
import { colors, radius } from '../theme';

export default StyleSheet.create({
  loadingCard: {
    alignItems: 'center',
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderWidth: 1,
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 22,
  },
  loadingIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  loadingTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  loadingText: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  stateCard: {
    alignItems: 'center',
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderWidth: 1,
    gap: 10,
    paddingHorizontal: 18,
    paddingVertical: 24,
  },
  stateIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  stateTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
  },
  stateText: {
    color: colors.mutedText,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    marginTop: 4,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  primaryButtonText: {
    color: colors.onPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  section: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderWidth: 1,
    gap: 14,
    padding: 18,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 19,
    fontWeight: '900',
  },
  sectionText: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 19,
  },
  emptyInlineText: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
  },
  inlineEmptyState: {
    alignItems: 'flex-start',
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  inlineEmptyStateIcon: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  inlineEmptyStateCopy: {
    flex: 1,
  },
  inlineEmptyStateTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  inlineEmptyStateText: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 4,
  },
  timelineList: {
    gap: 12,
  },
  filterRow: {
    gap: 8,
    paddingBottom: 4,
  },
  filterButton: {
    minHeight: 44,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  filterButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  filterButtonText: {
    color: colors.mutedText,
    fontSize: 13,
    fontWeight: '700',
  },
  filterButtonTextActive: {
    color: colors.primary,
  },
  loadMoreButton: {
    minHeight: 48,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadMoreButtonText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  timelineEventCard: {
    flexDirection: 'row',
    gap: 12,
  },
  timelineRail: {
    alignItems: 'center',
    width: 34,
  },
  timelineDot: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 17,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  timelineLine: {
    backgroundColor: colors.border,
    flex: 1,
    marginTop: 6,
    width: 2,
  },
  timelineEventContent: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    padding: 14,
  },
  timelineEventHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  timelineEventDate: {
    color: colors.mutedText,
    fontSize: 12,
    fontWeight: '700',
  },
  eventBadge: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.pill,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  eventBadgeText: {
    color: colors.labelText,
    fontSize: 11,
    fontWeight: '800',
  },
  timelineEventTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
    marginTop: 10,
  },
  timelineEventSummary: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 7,
  },
  timelineEventMeta: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 9,
  },
  insightCard: {
    alignItems: 'flex-start',
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  insightIcon: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  insightCopy: {
    flex: 1,
  },
  insightTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
  },
  insightText: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 5,
  },
  summaryProofCard: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    marginTop: 12,
    padding: 14,
  },
  summaryProofHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  summaryProofTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '900',
  },
  summaryProofText: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 21,
    marginTop: 10,
  },
  summaryProofMeta: {
    color: colors.mutedText,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 10,
  },
  modalBackdrop: {
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
    flex: 1,
    justifyContent: 'flex-end',
    padding: 18,
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderWidth: 1,
    gap: 10,
    padding: 18,
  },
  modalScroll: {
    maxHeight: '88%',
    width: '100%',
  },
  modalTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
  },
  modalSubtitle: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 4,
  },
  modalInput: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.text,
    fontSize: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  modalInputError: {
    borderColor: colors.danger,
  },
  modalFieldLabel: {
    color: colors.mutedText,
    fontSize: 12,
    fontWeight: '700',
  },
  modalFieldError: {
    color: colors.danger,
    fontSize: 12,
    lineHeight: 17,
  },
  modalErrorText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: '700',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  modalPrimaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
  },
  modalPrimaryButtonText: {
    color: colors.onPrimary,
    fontSize: 13,
    fontWeight: '900',
  },
  modalSecondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.pill,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
  },
  modalSecondaryButtonText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
})
