import { StyleSheet } from 'react-native';
import { colors, radius } from '../theme';

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 34,
    gap: 18,
  },
  heroShell: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderWidth: 1,
    overflow: 'hidden',
  },
  heroTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  heroActions: {
    flexDirection: 'row',
    gap: 8,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  actionButton: {
    alignItems: 'center',
    borderRadius: radius.pill,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
  },
  actionButtonPrimary: {
    backgroundColor: colors.primary,
  },
  actionButtonSecondary: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderWidth: 1,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '800',
  },
  actionButtonTextPrimary: {
    color: colors.onPrimary,
  },
  actionButtonTextSecondary: {
    color: colors.text,
  },
  heroPanel: {
    gap: 16,
    paddingHorizontal: 16,
    paddingBottom: 18,
    paddingTop: 18,
  },
  headerCopy: {
    flex: 1,
  },
  eyebrow: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  title: {
    color: colors.text,
    fontSize: 27,
    fontWeight: '900',
    lineHeight: 33,
    marginTop: 5,
  },
  subtitle: {
    color: colors.mutedText,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  heroBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  showcaseBadge: {
    alignItems: 'center',
    borderRadius: radius.pill,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  showcaseBadgeAccent: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryGlow,
    borderWidth: 1,
  },
  showcaseBadgeNeutral: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderWidth: 1,
  },
  showcaseBadgeText: {
    fontSize: 12,
    fontWeight: '800',
  },
  showcaseBadgeTextAccent: {
    color: colors.primary,
  },
  showcaseBadgeTextNeutral: {
    color: colors.labelText,
  },
  heroNarrativeCard: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    padding: 16,
  },
  heroNarrativeEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  heroNarrativeTitle: {
    color: colors.text,
    fontSize: 21,
    fontWeight: '900',
    marginTop: 8,
  },
  heroNarrativeText: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 8,
  },
  selectorSection: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderWidth: 1,
    gap: 14,
    padding: 18,
  },
  sectionHeading: {
    gap: 6,
  },
  sectionEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  vehicleScroller: {
    gap: 10,
    paddingRight: 16,
  },
  vehiclePagerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  vehiclePagerText: {
    color: colors.mutedText,
    fontSize: 12,
    fontWeight: '700',
  },
  vehiclePagerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  vehiclePagerButton: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.pill,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  vehiclePagerButtonDisabled: {
    opacity: 0.45,
  },
  vehiclePagerButtonText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  vehicleChip: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderWidth: 1,
    gap: 12,
    minWidth: 244,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  vehicleChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 4,
  },
  vehicleChipEyebrow: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  vehicleChipEyebrowActive: {
    color: colors.onPrimary,
    opacity: 0.78,
  },
  vehicleChipCopy: {
    flex: 1,
  },
  vehicleChipTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
    marginTop: 4,
  },
  vehicleChipTitleActive: {
    color: colors.onPrimary,
  },
  vehicleChipPlate: {
    color: colors.mutedText,
    fontSize: 12,
    marginTop: 3,
  },
  vehicleChipPlateActive: {
    color: colors.onPrimary,
    opacity: 0.82,
  },
  vehicleHero: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
  },
  vehicleHeroTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  vehicleHeroLabel: {
    color: colors.mutedText,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  vehicleHeroTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '900',
    marginTop: 8,
  },
  vehicleHeroPlate: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
    marginTop: 5,
  },
  vehicleHeroDescription: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 10,
  },
  vehicleHeroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  quickActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  metricsGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  metricCard: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  metricIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  metricValue: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '900',
  },
  metricValueWarm: {
    color: colors.primary,
  },
  metricLabel: {
    color: colors.mutedText,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
  },
  metricHelper: {
    color: colors.labelText,
    fontSize: 11,
    lineHeight: 15,
  }
})
