'use client'

import { useState } from 'react'
import { Wrench, CheckCircle2, AlertCircle, Clock, ShoppingBag,
         Shield, Sparkles, ExternalLink, BadgeCheck } from 'lucide-react'
import { vehicles as allVehicles, timelineEvents } from '@/lib/mockData'

// ── Config ────────────────────────────────────────────────────────────────────
const EVENT_CONFIG = {
  service:    { icon: Wrench,       label: 'Service',       color: '#22c55e', bg: 'rgba(34,197,94,0.1)'   },
  inspection: { icon: BadgeCheck,   label: 'Inspection',    color: '#3b82f6', bg: 'rgba(59,130,246,0.1)'  },
  repair:     { icon: Wrench,       label: 'Repair',        color: '#f07c00', bg: 'rgba(240,124,0,0.1)'   },
  alert:      { icon: AlertCircle,  label: 'Alert',         color: '#ef4444', bg: 'rgba(239,68,68,0.1)'   },
  purchase:   { icon: ShoppingBag,  label: 'Purchase',      color: '#a855f7', bg: 'rgba(168,85,247,0.1)'  },
  admin:      { icon: Clock,        label: 'Administrative',color: '#71717a', bg: 'rgba(113,113,122,0.1)' },
  insurance:  { icon: Shield,       label: 'Insurance',     color: '#14b8a6', bg: 'rgba(20,184,166,0.1)'  },
}

const AI_SUMMARIES = {
  v1: "ABC-1234 (Toyota Fortuner) has received consistent preventive maintenance. The most recent oil change and tire replacement suggest normal wear for a 45,000 km vehicle. No critical faults detected. Recommend scheduling brake fluid flush within the next 5,000 km.",
  v2: "XYZ-5678 (Honda Civic) recently underwent brake pad replacement and a tire purchase. Mileage pattern indicates heavy city use. Consider scheduling a suspension check at the next PMS.",
  v3: "QRS-9012 (Montero Sport) has an active coolant temperature sensor fault. This vehicle is currently under repair. Service history shows this may be related to extended idling patterns.",
  v4: "LMN-3456 (Ford Ranger) completed its 20,000 km PMS with no issues noted. Vehicle is in good standing. Next recommended service at 30,000 km.",
  v5: "DEF-7890 (Isuzu D-Max) has an open insurance inquiry and no recent service records. High mileage (95,000 km) suggests this vehicle is overdue for a comprehensive inspection.",
}

// ── Sub-components ────────────────────────────────────────────────────────────
function AISummaryCard({ vehicleId }) {
  const summary = AI_SUMMARIES[vehicleId] ?? 'No AI summary available for this vehicle yet.'
  return (
    <div className="relative overflow-hidden rounded-xl border p-5"
         style={{ borderColor: 'rgba(201,149,26,0.3)', background: 'rgba(201,149,26,0.05)' }}>
      {/* Coming Soon overlay */}
      <div className="absolute top-2.5 right-2.5">
        <span className="badge badge-gold text-[10px]">Powered by Claude API · Coming Soon</span>
      </div>

      <div className="flex items-start gap-3 mt-1">
        <div className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0"
             style={{ background: 'linear-gradient(135deg,#c9951a,#f07c00)' }}>
          <Sparkles size={16} className="text-white" />
        </div>
        <div>
          <p className="text-sm font-bold text-ink-primary">AI Service Interpretation</p>
          <p className="text-xs text-ink-muted mt-0.5">Technical notes simplified for your customer</p>
        </div>
      </div>

      <p className="mt-4 text-sm text-ink-secondary leading-relaxed border-l-2 pl-3"
         style={{ borderColor: '#c9951a' }}>
        {summary}
      </p>

      <div className="mt-3 flex items-center gap-2">
        <div className="w-2 h-2 rounded-full bg-amber-400 animate-pulse" />
        <p className="text-xs text-ink-muted">This interpretation will be generated by Claude AI in production.</p>
      </div>
    </div>
  )
}

function TimelineEvent({ event, isLast }) {
  const cfg    = EVENT_CONFIG[event.type] ?? EVENT_CONFIG.admin
  const Icon   = cfg.icon
  const isAdmin    = event.category === 'administrative'
  const isVerified = event.isVerified
  const dateStr    = new Date(event.date).toLocaleDateString('en-PH', {
    weekday: 'short', year: 'numeric', month: 'short', day: 'numeric',
  })

  return (
    <div className="relative flex gap-4">
      {/* Vertical connector */}
      {!isLast && (
        <div className="absolute left-4 top-10 bottom-0 w-px" style={{ backgroundColor: '#27272a' }} />
      )}

      {/* Icon node */}
      <div className="flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center border-2 z-10"
           style={{ backgroundColor: cfg.bg, borderColor: cfg.color }}>
        <Icon size={13} style={{ color: cfg.color }} />
      </div>

      {/* Content card */}
      <div className="flex-1 mb-5">
        <div className="card p-4 hover:bg-surface-hover transition-colors">
          <div className="flex flex-wrap items-start justify-between gap-2 mb-2">
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-xs font-bold uppercase tracking-wider px-2 py-0.5 rounded"
                    style={{ color: cfg.color, backgroundColor: cfg.bg }}>
                {cfg.label}
              </span>
              {isAdmin && (
                <span className="badge badge-gray">Administrative Event</span>
              )}
              {isVerified && (
                <span className="badge badge-green flex items-center gap-1">
                  <CheckCircle2 size={10} /> Verified by Staff
                </span>
              )}
            </div>
            <p className="text-xs text-ink-muted flex-shrink-0">{dateStr}</p>
          </div>

          <p className="text-sm text-ink-primary">{event.description}</p>

          <div className="flex flex-wrap items-center gap-3 mt-2.5">
            {event.technicianName && (
              <p className="text-xs text-ink-muted">
                <span className="text-ink-secondary font-medium">Technician:</span> {event.technicianName}
              </p>
            )}
            {event.jobOrderId && (
              <p className="text-xs text-ink-muted">
                <span className="text-ink-secondary font-medium">JO:</span>{' '}
                <span className="font-mono" style={{ color: '#f07c00' }}>{event.jobOrderId}</span>
              </p>
            )}
          </div>

          {/* Inspection record link — only for verified events */}
          {isVerified && event.jobOrderId && (
            <button className="mt-2.5 flex items-center gap-1.5 text-xs font-semibold hover:underline"
                    style={{ color: '#f07c00' }}>
              <ExternalLink size={11} /> View Inspection Record
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

// ── Main ──────────────────────────────────────────────────────────────────────
export default function VehicleTimeline() {
  const [selectedId, setSelectedId] = useState('v1')
  const [filter,     setFilter]     = useState('all')   // 'all' | 'verified' | 'admin'

  const vehicle = allVehicles.find(v => v.id === selectedId)

  const events = [...timelineEvents]
    .filter(e => e.vehicleId === selectedId)
    .filter(e => {
      if (filter === 'verified') return e.isVerified
      if (filter === 'admin')    return e.category === 'administrative'
      return true
    })
    .sort((a, b) => new Date(b.date) - new Date(a.date))

  return (
    <div className="space-y-5 max-w-3xl">

      {/* ── Controls ──────────────────────────────── */}
      <div className="flex flex-wrap gap-3">
        {/* Vehicle selector */}
        <select value={selectedId} onChange={e => setSelectedId(e.target.value)}
          className="select flex-1 min-w-[200px] max-w-xs">
          {allVehicles.map(v => (
            <option key={v.id} value={v.id}>{v.plate} — {v.owner} ({v.model})</option>
          ))}
        </select>

        {/* Filter chips */}
        <div className="flex gap-2">
          {[
            { key: 'all',      label: 'All Events' },
            { key: 'verified', label: 'Verified Milestones' },
            { key: 'admin',    label: 'Administrative' },
          ].map(f => (
            <button key={f.key} onClick={() => setFilter(f.key)}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all border ${
                filter === f.key
                  ? 'text-white border-transparent'
                  : 'border-surface-border text-ink-secondary hover:bg-surface-hover'
              }`}
              style={filter === f.key ? { backgroundColor: '#f07c00', borderColor: '#f07c00' } : {}}>
              {f.label}
            </button>
          ))}
        </div>
      </div>

      {/* ── Vehicle summary chip ──────────────────── */}
      {vehicle && (
        <div className="flex flex-wrap items-center gap-3 p-4 card">
          <div>
            <p className="text-sm font-bold text-ink-primary">{vehicle.owner}</p>
            <p className="text-xs text-ink-secondary">{vehicle.year} {vehicle.model} · {vehicle.color}</p>
          </div>
          <div className="ml-auto flex flex-wrap gap-2">
            <span className="font-mono text-xs px-2 py-1 rounded font-bold"
                  style={{ backgroundColor: 'rgba(240,124,0,0.1)', color: '#f07c00' }}>
              {vehicle.plate}
            </span>
            <span className={`badge ${vehicle.status === 'active' ? 'badge-green' : vehicle.status === 'maintenance' ? 'badge-orange' : 'badge-gray'}`}>
              {vehicle.status}
            </span>
          </div>
        </div>
      )}

      {/* ── AI Summary card ───────────────────────── */}
      <AISummaryCard vehicleId={selectedId} />

      {/* ── Timeline ──────────────────────────────── */}
      <div className="pt-2">
        {events.length === 0
          ? (
            <div className="text-center py-16 text-ink-muted text-sm">
              No events found for this filter.
            </div>
          )
          : events.map((ev, i) => (
              <TimelineEvent key={ev.id} event={ev} isLast={i === events.length - 1} />
            ))
        }
      </div>
    </div>
  )
}
