import { StyleSheet } from 'react-native';

import { colors, radius } from '../../../theme';
import { createPlatformShadow } from '../../../utils/platformShadow';

export default StyleSheet.create({
  sectionHeading: {
    color: colors.labelText,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    marginBottom: 14,
  },
  rewardCard: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: radius.large,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 14,
  },
  rewardCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  rewardIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  rewardCopy: {
    flex: 1,
  },
  rewardTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  rewardPoints: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
  },
  claimButton: {
    minWidth: 74,
    minHeight: 44,
    paddingHorizontal: 16,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...createPlatformShadow({
      color: colors.primary,
      height: 8,
      opacity: 0.24,
      radius: 18,
      elevation: 3,
    }),
  },
  claimButtonLocked: {
    backgroundColor: '#272D43',
    ...createPlatformShadow({ opacity: 0, elevation: 0 }),
  },
  claimButtonText: {
    color: colors.onPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  claimButtonTextLocked: {
    color: colors.mutedText,
  },
  rewardProgressMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingLeft: 54,
  },
  rewardProgressLabel: {
    color: colors.mutedText,
    fontSize: 12,
  },
  rewardProgressValue: {
    fontSize: 12,
    fontWeight: '800',
  },
  rewardProgressTrack: {
    height: 7,
    marginLeft: 54,
    borderRadius: radius.pill,
    backgroundColor: '#2B3043',
    overflow: 'hidden',
  },
  rewardProgressFill: {
    height: '100%',
    borderRadius: radius.pill,
  },
  rewardHelperText: {
    marginTop: 10,
    marginLeft: 54,
    color: colors.mutedText,
    fontSize: 12,
    lineHeight: 18,
  },
  infoPanel: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: radius.large,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    marginBottom: 14,
  },
  infoPanelHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  infoPanelHeaderCopy: {
    flex: 1,
  },
  infoPanelTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 8,
  },
  infoPanelText: {
    color: colors.mutedText,
    fontSize: 14,
    lineHeight: 22,
  },
  infoPanelPill: {
    minHeight: 30,
    paddingHorizontal: 12,
    borderRadius: radius.pill,
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primaryGlow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoPanelPillText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  infoPanelSummaryRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  infoPanelSummaryCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: radius.medium,
    padding: 14,
  },
  infoPanelSummaryLabel: {
    color: colors.labelText,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  infoPanelSummaryValue: {
    color: colors.primary,
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 4,
  },
  infoPanelSummaryValueMuted: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 4,
  },
  infoPanelSummaryText: {
    color: colors.mutedText,
    fontSize: 12,
    lineHeight: 18,
  },
  infoPanelActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  infoPanelPrimaryAction: {
    flexGrow: 1,
    minWidth: 170,
    marginTop: 0,
  },
  insuranceSelectionMeta: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
    marginTop: -2,
    marginBottom: 10,
  },
  insuranceLauncherDisabled: {
    opacity: 0.58,
  },
  infoPanelSecondaryAction: {
    minHeight: 54,
    paddingHorizontal: 16,
    borderRadius: radius.medium,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  infoPanelSecondaryActionText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  profileSettingsList: {
    marginTop: 6,
    marginBottom: 14,
  },
  menuRow: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.medium,
    backgroundColor: colors.surfaceStrong,
    marginBottom: 12,
  },
  menuRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  menuIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primarySoft,
    marginRight: 14,
  },
  menuIconWrapDanger: {
    backgroundColor: '#FEE2E2',
  },
  menuCopy: {
    flex: 1,
  },
  menuLabel: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  menuLabelDanger: {
    color: colors.danger,
  },
  menuMeta: {
    color: colors.mutedText,
    fontSize: 12,
    marginTop: 2,
  },
  menuArrow: {
    color: colors.mutedText,
    fontSize: 20,
    fontWeight: '700',
    marginLeft: 12,
  },
  menuArrowDanger: {
    color: colors.danger,
  },
  signOutRow: {
    minHeight: 62,
    borderRadius: radius.medium,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 107, 0.55)',
    backgroundColor: colors.surfaceStrong,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  signOutRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  signOutRowText: {
    color: colors.danger,
    fontSize: 15,
    fontWeight: '800',
    marginLeft: 10,
  },
  subHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 22,
  },
});
