import { Platform, StyleSheet } from 'react-native';

import { colors, radius } from '../../../theme';
import {
  BOTTOM_NAV_HEIGHT,
  DASHBOARD_WEB_SCROLL_HEIGHT,
} from '../dashboardNavigationModel.mjs';

export default StyleSheet.create({
  flex: {
    flex: 1,
    minHeight: 0,
    flexShrink: 1,
  },
  safeArea: {
    flex: 1,
    minHeight: 0,
    flexShrink: 1,
    backgroundColor: colors.background,
    ...Platform.select({
      web: {
        height: '100vh',
        maxHeight: '100vh',
        minHeight: '100vh',
        overflow: 'hidden',
        overflowX: 'hidden',
      },
    }),
  },
  screen: {
    flex: 1,
    minHeight: 0,
    flexShrink: 1,
    backgroundColor: colors.background,
    position: 'relative',
    ...Platform.select({
      web: {
        height: '100%',
        overflow: 'hidden',
        overflowX: 'hidden',
      },
    }),
  },
  contentArea: {
    flex: 1,
    minHeight: 0,
    flexShrink: 1,
    backgroundColor: colors.background,
    paddingBottom: Platform.OS === 'web' ? 0 : BOTTOM_NAV_HEIGHT,
    ...Platform.select({
      web: {
        height: DASHBOARD_WEB_SCROLL_HEIGHT,
        maxHeight: DASHBOARD_WEB_SCROLL_HEIGHT,
        overflow: 'hidden',
      },
    }),
  },
  scrollView: {
    flex: 1,
    minHeight: 0,
    flexShrink: 1,
  },
  scrollRegion: {
    flex: 1,
    minHeight: 0,
    flexShrink: 1,
    ...Platform.select({
      web: {
        display: 'flex',
        flexDirection: 'column',
        height: DASHBOARD_WEB_SCROLL_HEIGHT,
        maxHeight: DASHBOARD_WEB_SCROLL_HEIGHT,
        overflowY: 'scroll',
        overflowX: 'hidden',
      },
    }),
  },
  webScrollContent: {
    minHeight: '100%',
    width: '100%',
  },
  storeStickyHeader: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
    backgroundColor: colors.background,
    zIndex: 2,
  },
  storeStickyHeaderCompact: {
    paddingHorizontal: 14,
  },
  storeScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: Platform.OS === 'web' ? 88 : BOTTOM_NAV_HEIGHT + 88,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: Platform.OS === 'web' ? 88 : BOTTOM_NAV_HEIGHT + 88,
  },
  scrollContentCompact: {
    paddingHorizontal: 14,
  },
  menuRootContent: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: Platform.OS === 'web' ? 88 : BOTTOM_NAV_HEIGHT + 88,
  },
  homeScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: Platform.OS === 'web' ? 104 : BOTTOM_NAV_HEIGHT + 104,
  },
  homeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
    paddingRight: 4,
  },
  homeBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeBrandBadge: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  homeBrandEyebrow: {
    color: colors.labelText,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.4,
  },
  homeBrandTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
  },
  homeHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  homeAvatarImage: {
    width: '100%',
    height: '100%',
  },
  homeAvatarText: {
    color: colors.onPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  homeNotificationBanner: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 18,
  },
  homeNotificationIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  homeNotificationCopy: {
    flex: 1,
    paddingRight: 10,
  },
  homeNotificationMeta: {
    color: colors.labelText,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 4,
  },
  homeNotificationTime: {
    color: colors.mutedText,
    fontWeight: '600',
  },
  homeNotificationTitle: {
    color: colors.text,
    fontSize: 19,
    fontWeight: '800',
    marginBottom: 4,
  },
  homeNotificationText: {
    color: '#A9B1D2',
    fontSize: 14,
    lineHeight: 21,
  },
  homeNotificationClose: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeGreeting: {
    color: colors.labelText,
    fontSize: 16,
    marginBottom: 4,
  },
  homeNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  homeName: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 28,
    flexShrink: 1,
  },
  homeWave: {
    fontSize: 22,
    marginLeft: 8,
  },
  homeStatusCard: {
    backgroundColor: '#132C59',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(84, 147, 255, 0.32)',
    padding: 16,
    marginBottom: 18,
    overflow: 'hidden',
  },
  homeStatusCardIdle: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.border,
  },
  homeStatusHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 16,
  },
  homeStatusHeaderVeryCompact: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  homeStatusCopy: {
    flex: 1,
    minWidth: 0,
  },
  homeStatusBadge: {
    color: '#7FB4FF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    marginBottom: 8,
  },
  homeStatusBadgeIdle: {
    color: colors.mutedText,
  },
  homeStatusTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 6,
    lineHeight: 20,
  },
  homeStatusSubtitle: {
    color: '#A2B4D7',
    fontSize: 14,
    lineHeight: 20,
    maxWidth: '100%',
  },
  homeStatusHelper: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 8,
    opacity: 0.9,
  },
  homeTrackButton: {
    flexShrink: 0,
    minHeight: 44,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(65, 124, 230, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(132, 179, 255, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeTrackButtonIdle: {
    backgroundColor: '#1C2233',
    borderColor: colors.borderSoft,
  },
  homeTrackButtonVeryCompact: {
    alignSelf: 'stretch',
  },
  homeTrackButtonText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  homeTrackButtonTextIdle: {
    color: colors.labelText,
  },
  homeProgressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  homeProgressLabel: {
    color: '#90A3CB',
    fontSize: 12,
  },
  homeProgressTrack: {
    height: 6,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    overflow: 'hidden',
  },
  homeProgressFill: {
    height: '100%',
    borderRadius: radius.pill,
    backgroundColor: '#63A5FF',
  },
  homeVehicleCard: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 76,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  homeVehicleImage: {
    width: '100%',
    height: 170,
  },
  homeVehicleShade: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 78,
    height: 92,
    backgroundColor: 'rgba(10, 13, 20, 0.55)',
  },
  homeVehicleTopCopy: {
    flex: 1,
    minWidth: 0,
  },
  homeVehicleTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 4,
    lineHeight: 23,
  },
  homeVehicleMeta: {
    color: '#A1A9C6',
    fontSize: 14,
    lineHeight: 19,
  },
  homeVehicleStats: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
  },
  homeVehicleStatItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
  },
  homeVehicleStatDivider: {
    width: 1,
    backgroundColor: colors.borderSoft,
  },
  homeVehicleStatValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 4,
    lineHeight: 24,
  },
  homeVehicleStatLabel: {
    color: colors.mutedText,
    fontSize: 13,
    textAlign: 'center',
  },
  homeVehicleTierValue: {
    color: '#FFC500',
  },
  homeSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  homeSectionLabel: {
    color: colors.labelText,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  quickActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
    gap: 8,
  },
  quickActionsRowCompact: {
    flexWrap: 'wrap',
    rowGap: 14,
  },
  quickActionCardContainer: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
  },
  homeVehicleIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homePrimaryBookingButton: {
    minHeight: 52,
    borderRadius: 12,
    backgroundColor: colors.primary,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  homePrimaryBookingButtonText: {
    color: colors.onPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
});
