import { Platform, StyleSheet } from 'react-native';

import { colors, radius } from '../../../theme';
import { createPlatformShadow } from '../../../utils/platformShadow';
import {
  BOTTOM_NAV_HEIGHT,
  DASHBOARD_WEB_SCROLL_HEIGHT,
} from '../dashboardNavigationModel.mjs';

export default StyleSheet.create({
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  backButtonText: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  subHeaderCopy: {
    flex: 1,
  },
  subHeaderTitle: {
    color: colors.text,
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 4,
  },
  subHeaderSubtitle: {
    color: colors.mutedText,
    fontSize: 14,
    lineHeight: 21,
  },
  profileImageSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  largeAvatarWrap: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 12,
  },
  largeProfileImage: {
    width: '100%',
    height: '100%',
  },
  largeAvatarInitials: {
    color: colors.primary,
    fontSize: 32,
    fontWeight: '800',
  },
  changeImageLink: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  genderSection: {
    marginBottom: 18,
  },
  fieldLabel: {
    color: colors.mutedText,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  genderRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  genderChip: {
    minHeight: 42,
    paddingHorizontal: 14,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  genderChipSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  genderChipText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  genderChipTextSelected: {
    color: colors.primary,
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: radius.medium,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: colors.onPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryButton: {
    minHeight: 52,
    borderRadius: radius.medium,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    backgroundColor: colors.background,
  },
  editProfileButton: {
    marginBottom: 18,
  },
  secondaryButtonText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '700',
  },
  bookingReservationPaymentActions: {
    marginTop: 8,
  },
  bookingReservationPaymentHint: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 10,
  },
  bookingReservationPaymentWarning: {
    color: '#FCA5A5',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 10,
  },
  checkoutBackButton: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 0,
  },
  deleteSection: {
    marginTop: 34,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
  },
  deleteTitle: {
    color: colors.danger,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  deleteDescription: {
    color: colors.mutedText,
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 16,
  },
  deleteButton: {
    minHeight: 50,
    borderRadius: radius.medium,
    borderWidth: 1,
    borderColor: colors.danger,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEF2F2',
  },
  deleteButtonText: {
    color: colors.danger,
    fontSize: 15,
    fontWeight: '800',
  },
  passwordFieldContainer: {
    marginBottom: 18,
  },
  passwordInputWrap: {
    minHeight: 54,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.medium,
    paddingLeft: 14,
    paddingRight: 10,
    backgroundColor: colors.input,
    flexDirection: 'row',
    alignItems: 'center',
  },
  passwordInputWrapError: {
    borderColor: colors.danger,
  },
  passwordInput: {
    flex: 1,
    color: colors.text,
    fontSize: 15,
    paddingVertical: 14,
  },
  eyeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
  },
  eyeButtonText: {
    color: colors.mutedText,
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 4,
  },
  errorText: {
    color: colors.danger,
    fontSize: 12,
    marginTop: 6,
    lineHeight: 18,
  },
  infoBlock: {
    paddingVertical: 18,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
  },
  infoTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
  },
  infoText: {
    color: colors.mutedText,
    fontSize: 14,
    lineHeight: 22,
  },
  comingSoonWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  comingSoonTitle: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '800',
    marginTop: 14,
    marginBottom: 6,
  },
  comingSoonSubtitle: {
    color: colors.mutedText,
    fontSize: 16,
  },
  notificationsPanel: {
    position: 'absolute',
    top: 86,
    right: 12,
    width: Platform.OS === 'web' ? 388 : undefined,
    left: Platform.OS === 'web' ? 12 : 12,
    maxHeight: 600,
    backgroundColor: colors.surfaceStrong,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    zIndex: 2200,
    ...createPlatformShadow({
      color: colors.shadow,
      height: 18,
      opacity: 0.3,
      radius: 24,
      elevation: 8,
    }),
    overflow: 'hidden',
  },
  notificationsPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  notificationsPanelTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  notificationsPanelSubtitle: {
    color: colors.mutedText,
    fontSize: 13,
    marginTop: 4,
  },
  notificationsPanelHelperText: {
    color: colors.labelText,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
    maxWidth: 220,
  },
  notificationsPanelActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  notificationsHeaderButton: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    marginRight: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  notificationsHeaderButtonText: {
    color: colors.labelText,
    fontSize: 13,
    marginLeft: 4,
  },
  notificationsPanelClose: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationsList: {
    maxHeight: 520,
  },
  notificationsListContent: {
    paddingBottom: 12,
  },
  notificationsSummaryRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  notificationsSummaryCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: radius.medium,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  notificationsSummaryLabel: {
    color: colors.labelText,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 6,
  },
  notificationsSummaryValue: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '900',
  },
  notificationsSummaryValueMuted: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
  },
  notificationRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  notificationIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  notificationCopy: {
    flex: 1,
    paddingRight: 10,
  },
  notificationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 4,
  },
  notificationUnreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
    marginRight: 8,
  },
  notificationRowTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  notificationStatusPill: {
    minHeight: 24,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationStatusPillAction: {
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primaryGlow,
  },
  notificationStatusPillInformational: {
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  notificationStatusPillText: {
    fontSize: 11,
    fontWeight: '800',
  },
  notificationStatusPillTextAction: {
    color: colors.primary,
  },
  notificationStatusPillTextInformational: {
    color: colors.labelText,
  },
});
