import { Platform, StyleSheet } from 'react-native';

import { colors, radius } from '../../../theme';
import {
  BOTTOM_NAV_HEIGHT,
  DASHBOARD_WEB_SCROLL_HEIGHT,
} from '../dashboardNavigationModel.mjs';

export default StyleSheet.create({
  bookingDiscoveryBannerCopyWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingRight: 12,
  },
  bookingDiscoveryBannerCopyWrapCompact: {
    minWidth: '100%',
    paddingRight: 0,
  },
  bookingDiscoveryBannerIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  bookingDiscoveryBannerCopy: {
    flex: 1,
  },
  bookingDiscoveryBannerTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  bookingDiscoveryBannerText: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
  },
  bookingDiscoveryRefreshButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingStatePanel: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 18,
  },
  bookingStatePanelHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  bookingStatePanelIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  bookingStatePanelCopy: {
    flex: 1,
  },
  bookingStatePanelTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  bookingStatePanelText: {
    color: colors.mutedText,
    fontSize: 14,
    lineHeight: 22,
  },
  bookingStatePanelButton: {
    alignSelf: 'flex-start',
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: radius.pill,
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primaryGlow,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
  },
  bookingStatePanelButtonText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  bookingServiceCard: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  bookingServiceCardCompact: {
    alignItems: 'flex-start',
  },
  bookingServiceCardSelected: {
    borderColor: '#5A4608',
    backgroundColor: '#1E2232',
  },
  bookingServiceCardDisabled: {
    opacity: 0.52,
  },
  bookingServiceIconWrap: {
    width: 48,
    height: 48,
    flexShrink: 0,
    borderRadius: 16,
    backgroundColor: '#252B42',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  bookingServiceIconWrapDisabled: {
    backgroundColor: '#1D2233',
  },
  bookingServiceCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 10,
  },
  bookingServiceCopyCompact: {
    paddingRight: 0,
  },
  bookingServiceBody: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  bookingServiceBodyCompact: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 10,
  },
  bookingServiceTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 4,
  },
  bookingServiceTitle: {
    color: colors.text,
    flexShrink: 1,
    fontSize: 15,
    fontWeight: '800',
    marginRight: 8,
    minWidth: 0,
  },
  bookingPopularBadge: {
    minHeight: 20,
    paddingHorizontal: 8,
    borderRadius: radius.pill,
    backgroundColor: '#6C3B07',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingPopularBadgeText: {
    color: '#FFB067',
    fontSize: 10,
    fontWeight: '800',
  },
  bookingUnavailableBadge: {
    minHeight: 20,
    paddingHorizontal: 8,
    borderRadius: radius.pill,
    backgroundColor: '#262A3A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingUnavailableBadgeText: {
    color: colors.mutedText,
    fontSize: 10,
    fontWeight: '800',
  },
  bookingServiceSubtitle: {
    color: colors.mutedText,
    flexShrink: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  bookingDisabledText: {
    color: '#7981A2',
  },
  bookingDisabledSubtext: {
    color: '#666D89',
  },
  bookingServiceMeta: {
    alignItems: 'flex-end',
  },
  bookingServiceMetaCompact: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 10,
  },
  bookingServicePrice: {
    color: colors.labelText,
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 8,
  },
  bookingServiceDurationRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bookingServiceDuration: {
    color: colors.mutedText,
    fontSize: 12,
    marginLeft: 4,
  },
  bookingVehicleBadge: {
    minHeight: 20,
    paddingHorizontal: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingVehicleBadgeText: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: '800',
  },
  bookingVehicleMeta: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  bookingVehicleMetaCompact: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 10,
  },
  bookingVehicleMetaLabel: {
    color: colors.mutedText,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  bookingVehicleMetaValue: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  bookingDateScroller: {
    flexGrow: 0,
    marginBottom: 22,
  },
  bookingDateRow: {
    paddingRight: 12,
  },
  bookingDatePressable: {
    flexGrow: 0,
    flexShrink: 0,
  },
  bookingDateCard: {
    width: '100%',
    flexGrow: 0,
    flexShrink: 0,
    minHeight: 64,
    borderRadius: 14,
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 12,
  },
  bookingDateCardCompact: {
    minHeight: 60,
    paddingVertical: 8,
  },
  bookingDateCardActive: {
    borderColor: colors.primary,
    borderWidth: 2,
  },
  bookingDateCardSuccess: {
    backgroundColor: colors.successSoft,
    borderColor: colors.success,
  },
  bookingDateCardLimited: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  bookingDateCardDanger: {
    backgroundColor: colors.dangerSoft,
    borderColor: colors.danger,
  },
  bookingDateCardDisabled: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.borderSoft,
  },
  bookingDateLeading: {
    minWidth: 64,
  },
  bookingDateBody: {
    flex: 1,
    minWidth: 0,
  },
  bookingDateDayRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
    marginTop: 2,
  },
  bookingDateWeekday: {
    color: colors.labelText,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  bookingDateDay: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 24,
  },
  bookingDateMonth: {
    color: colors.labelText,
    fontSize: 13,
    fontWeight: '700',
  },
  bookingDateStatusBadge: {
    flexShrink: 1,
    minHeight: 24,
    borderRadius: radius.pill,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  bookingDateStatusBadgeSuccess: {
    backgroundColor: colors.success,
  },
  bookingDateStatusBadgeWarning: {
    backgroundColor: colors.primary,
  },
  bookingDateStatusBadgeDanger: {
    backgroundColor: colors.danger,
  },
  bookingDateStatusBadgeMuted: {
    backgroundColor: colors.surfaceMuted,
  },
  bookingDateStatusText: {
    color: colors.onPrimary,
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  bookingDateCapacityText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  bookingDateDetailText: {
    color: colors.mutedText,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
  },
  bookingDateHint: {
    color: colors.mutedText,
    fontSize: 12,
    lineHeight: 18,
    marginTop: -4,
    marginBottom: 12,
  },
  bookingAvailabilityWindowCard: {
    borderRadius: radius.large,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    padding: 16,
    gap: 14,
    marginBottom: 20,
  },
  bookingAvailabilityToolbar: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  bookingAvailabilityToolbarCompact: {
    flexWrap: 'wrap',
  },
  bookingAvailabilityCopy: {
    flex: 1,
    gap: 4,
  },
  bookingAvailabilityTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  bookingAvailabilityText: {
    color: colors.mutedText,
    fontSize: 12,
    lineHeight: 18,
  },
  bookingAvailabilityActions: {
    flexDirection: 'row',
    gap: 8,
  },
});
