import { Platform, StyleSheet } from 'react-native';

import { colors, radius } from '../../../theme';
import { createPlatformShadow } from '../../../utils/platformShadow';
import {
  BOTTOM_NAV_HEIGHT,
  DASHBOARD_WEB_SCROLL_HEIGHT,
} from '../dashboardNavigationModel.mjs';

export default StyleSheet.create({
  bookingAvailabilityActionsCompact: {
    width: '100%',
    justifyContent: 'flex-end',
  },
  bookingAvailabilityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 12,
  },
  bookingAvailabilityGridCompact: {
    gap: 8,
  },
  bookingAvailabilitySelectionCard: {
    borderRadius: radius.medium,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surface,
    padding: 14,
    gap: 8,
  },
  bookingAvailabilitySelectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  bookingAvailabilitySelectionHeaderCompact: {
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  bookingAvailabilitySelectionTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  bookingAvailabilitySelectionMeta: {
    color: colors.mutedText,
    fontSize: 12,
    lineHeight: 18,
  },
  bookingPagerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: -4,
    marginBottom: 12,
    gap: 12,
  },
  bookingPagerRowCompact: {
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  bookingPagerText: {
    color: colors.mutedText,
    fontSize: 12,
    fontWeight: '700',
  },
  bookingPagerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bookingPagerActionsCompact: {
    width: '100%',
    justifyContent: 'flex-end',
  },
  bookingPagerButton: {
    minWidth: 44,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surfaceStrong,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingPagerButtonDisabled: {
    opacity: 0.45,
  },
  bookingPagerButtonText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
    marginHorizontal: 4,
  },
  bookingVehicleSearchWrap: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    marginBottom: 12,
  },
  bookingVehicleSearchInput: {
    flex: 1,
    color: colors.text,
    fontSize: 15,
    marginLeft: 10,
    paddingVertical: 12,
  },
  bookingTimeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 10,
    marginBottom: 18,
  },
  bookingTimeSlotContainer: {
    width: '48%',
  },
  bookingTimeSlotContainerCompact: {
    width: '100%',
  },
  bookingTimeSlot: {
    minHeight: 38,
    borderRadius: 14,
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    paddingVertical: 8,
  },
  bookingTimeSlotCompact: {
    alignItems: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  bookingTimeSlotActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  bookingTimeSlotDisabled: {
    backgroundColor: '#1B2030',
    borderColor: colors.borderSoft,
  },
  bookingTimeSlotText: {
    color: colors.labelText,
    fontSize: 16,
    fontWeight: '800',
  },
  bookingTimeSlotSubtext: {
    color: colors.mutedText,
    fontSize: 12,
    marginTop: 4,
  },
  bookingTimeSlotTextActive: {
    color: colors.onPrimary,
  },
  bookingTimeSlotSubtextActive: {
    color: colors.onPrimary,
  },
  bookingTimeSlotTextDisabled: {
    color: '#6E7594',
  },
  bookingTimeSlotReason: {
    color: '#6E7594',
    fontSize: 10,
    fontWeight: '700',
    marginTop: 3,
    textTransform: 'uppercase',
  },
  bookingTimeSlotReasonActive: {
    color: colors.onPrimary,
  },
  bookingInfoPanel: {
    width: '100%',
    backgroundColor: colors.surfaceStrong,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    padding: 16,
  },
  bookingInfoPanelTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 6,
  },
  bookingInfoPanelText: {
    color: colors.mutedText,
    fontSize: 14,
    lineHeight: 22,
  },
  bookingSummaryCard: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    marginBottom: 20,
  },
  bookingSummaryTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 14,
  },
  bookingSummaryRow: {
    marginBottom: 12,
  },
  bookingSummaryLabel: {
    color: colors.mutedText,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  bookingSummaryValue: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
  },
  bookingSummaryNote: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 21,
    marginTop: 4,
  },
  bookingReviewEditActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 12,
  },
  bookingReviewEditButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  bookingReviewEditText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '800',
  },
  bookingHistoryToolbar: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bookingHistoryToolbarText: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
    maxWidth: 250,
  },
  bookingHistoryList: {
    marginBottom: 16,
  },
  bookingHistoryCard: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 12,
  },
  bookingHistoryCardActive: {
    borderColor: '#5A4608',
    backgroundColor: '#1E2232',
  },
  bookingHistoryCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  bookingHistoryReference: {
    color: colors.mutedText,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.7,
  },
  bookingHistoryStatusPill: {
    minHeight: 26,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingHistoryStatusText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '800',
  },
  bookingHistoryTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
  },
  bookingServiceChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  bookingServiceChipRowCompact: {
    marginBottom: 8,
  },
  bookingServiceChip: {
    minHeight: 28,
    paddingHorizontal: 12,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingServiceChipText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  bookingHistoryMeta: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
  },
  bookingNotesCard: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    marginBottom: 24,
  },
  bookingNotesInput: {
    minHeight: 84,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.background,
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  bookingConfirmButton: {
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    ...createPlatformShadow({
      color: colors.primary,
      height: 12,
      opacity: 0.18,
      radius: 22,
      elevation: 4,
    }),
  },
  bookingConfirmButtonDisabled: {
    backgroundColor: '#7C420C',
    ...createPlatformShadow({ opacity: 0, elevation: 0 }),
  },
  bookingConfirmButtonText: {
    color: colors.onPrimary,
    fontSize: 16,
    fontWeight: '800',
    marginRight: 6,
  },
  bookingConfirmButtonTextDisabled: {
    color: '#B88D63',
  },
  trackingSummaryCard: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    marginBottom: 16,
  },
  trackingSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  trackingReferenceText: {
    color: colors.mutedText,
    fontSize: 13,
  },
  trackingStatusPill: {
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trackingStatusPillActive: {
    backgroundColor: 'rgba(57, 129, 255, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(57, 129, 255, 0.35)',
  },
  trackingStatusPillIdle: {
    backgroundColor: '#1C2233',
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  trackingStatusPillText: {
    color: '#6CA9FF',
    fontSize: 13,
    fontWeight: '800',
  },
  trackingStatusPillTextIdle: {
    color: colors.mutedText,
  },
  trackingSummaryTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 10,
  },
  trackingRequestedServicesSection: {
    marginBottom: 16,
  },
  trackingMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  trackingMetaItem: {
    width: '48%',
    marginBottom: 14,
  },
  trackingMetaItemWide: {
    width: '100%',
    marginBottom: 14,
  },
  trackingMetaLabel: {
    color: colors.mutedText,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  trackingMetaValue: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 21,
  },
});
