import { Platform, StyleSheet } from 'react-native';

import { colors, radius } from '../../../theme';
import {
  BOTTOM_NAV_HEIGHT,
  DASHBOARD_WEB_SCROLL_HEIGHT,
} from '../dashboardNavigationModel.mjs';

export default StyleSheet.create({
  quickActionCardContainerCompact: {
    flexBasis: '47%',
    flexGrow: 1,
    flex: 0,
  },
  quickActionCard: {
    alignItems: 'center',
    width: '100%',
  },
  quickActionIconWrap: {
    width: '100%',
    minHeight: 54,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  quickActionIconWrapCompact: {
    width: '100%',
    minHeight: 50,
  },
  quickActionIconInner: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionLabel: {
    color: colors.labelText,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 17,
    minHeight: 34,
  },
  homePmsCard: {
    backgroundColor: 'rgba(96, 52, 14, 0.35)',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255, 122, 0, 0.25)',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 22,
  },
  homePmsIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: 'rgba(255, 122, 0, 0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  homePmsCopy: {
    flex: 1,
    paddingRight: 10,
  },
  homePmsTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
    lineHeight: 21,
  },
  homePmsSubtitle: {
    color: '#C3A78F',
    fontSize: 14,
    lineHeight: 20,
  },
  homePmsButton: {
    minWidth: 58,
    minHeight: 44,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homePmsButtonText: {
    color: colors.onPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  homeViewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    paddingHorizontal: 4,
  },
  homeViewAllText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
    marginRight: 2,
  },
  homeServiceRow: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  homeServiceRowCompact: {
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 12,
  },
  homeServiceRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
    paddingRight: 10,
  },
  homeServiceRowLeftCompact: {
    paddingRight: 0,
  },
  homeServiceIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: '#242A40',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  homeServiceCopy: {
    flex: 1,
    minWidth: 0,
  },
  homeServiceTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  homeServiceDate: {
    color: colors.mutedText,
    fontSize: 14,
  },
  homeServiceStatusPill: {
    flexShrink: 0,
    minHeight: 28,
    paddingHorizontal: 12,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(18, 215, 100, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeServiceStatusText: {
    color: '#12D764',
    fontSize: 12,
    fontWeight: '800',
  },
  homeOfferCard: {
    backgroundColor: '#202443',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#383E64',
    padding: 18,
    marginTop: 10,
    overflow: 'hidden',
  },
  homeOfferEyebrow: {
    color: '#FFC500',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 12,
  },
  homeOfferTitle: {
    color: colors.text,
    fontSize: 19,
    fontWeight: '800',
    marginBottom: 8,
  },
  homeOfferSubtitle: {
    color: '#A9B1D2',
    fontSize: 15,
    lineHeight: 22,
    maxWidth: '78%',
    marginBottom: 16,
  },
  homeOfferSubtitleCompact: {
    maxWidth: '100%',
  },
  homeOfferButton: {
    alignSelf: 'flex-start',
    minHeight: 44,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeOfferButtonText: {
    color: colors.onPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  homeOfferCircle: {
    position: 'absolute',
    right: -34,
    top: -10,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255, 122, 0, 0.12)',
  },
  timelineScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: Platform.OS === 'web' ? 100 : BOTTOM_NAV_HEIGHT + 100,
  },
  timelineHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  timelineTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 4,
  },
  timelineSubtitle: {
    color: colors.mutedText,
    fontSize: 13,
  },
  timelineFilterIconButton: {
    width: 36,
    height: 36,
    borderRadius: 14,
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  garageHeroCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
    backgroundColor: '#17233F',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(84, 147, 255, 0.28)',
    padding: 18,
    marginBottom: 16,
    overflow: 'hidden',
  },
  garageHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  garageHeroEyebrow: {
    color: '#7FB4FF',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  garageHeroTitle: {
    color: colors.text,
    fontSize: 21,
    fontWeight: '900',
    lineHeight: 26,
    marginBottom: 8,
  },
  garageHeroText: {
    color: '#A9B8DA',
    fontSize: 14,
    lineHeight: 21,
  },
  garageHeroBadge: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(84, 147, 255, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(132, 179, 255, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  garageHeroBadgeText: {
    color: '#BBD3FF',
    fontSize: 12,
    fontWeight: '800',
  },
  garageVehicleList: {
    gap: 12,
    marginBottom: 16,
  },
  garageVehicleCard: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 15,
  },
  garageVehicleCardSelected: {
    borderColor: colors.primary,
    backgroundColor: '#211F2F',
  },
  garageVehicleHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    minHeight: 44,
  },
  garageVehicleIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  garageVehicleCopy: {
    flex: 1,
    minWidth: 0,
  },
  garageVehicleTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  garageVehicleTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '900',
    lineHeight: 22,
  },
  garageVehicleMeta: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 5,
  },
  garageVehicleRoute: {
    color: colors.labelText,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 6,
  },
  garagePrimaryPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radius.pill,
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primaryGlow,
  },
  garagePrimaryPillText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '900',
  },
  garageActionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  garageActionButton: {
    flexGrow: 1,
    minWidth: 86,
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  garageActionText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  garagePagerRow: {
    minHeight: 52,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  garagePagerText: {
    flex: 1,
    color: colors.mutedText,
    fontSize: 12,
    lineHeight: 18,
  },
  garagePagerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  garagePagerButton: {
    width: 44,
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  garagePagerButtonDisabled: {
    opacity: 0.42,
  },
  garagePagerPage: {
    minWidth: 46,
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  garagePlannedActionsCard: {
    backgroundColor: colors.surfaceStrong,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 16,
  },
  garageRouteCard: {
    backgroundColor: '#1B2133',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 20,
  },
  garagePlannedTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 6,
  },
  garagePlannedText: {
    color: colors.mutedText,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 12,
  },
  garagePlannedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
  },
});
