import { AccessoriesCatalogView } from './AccessoriesCatalogScreen';
import { AccessoryProductView } from './AccessoryProductScreen';
import { AccessoryCartView } from './AccessoryCartScreen';
import { AccessoryCheckoutView } from './AccessoryCheckoutScreen';
import { AccessoryOrdersView } from './AccessoryOrdersScreen';
import { AccessoryOrderDetailView } from './AccessoryOrderDetailScreen';

const noop = () => {};
const variant = { id: 'variant-1', productId: 'product-1', name: 'White beam', sku: 'LIGHT-001', priceCents: 189900, currencyCode: 'PHP', attributes: {} };
const product = { id: 'product-1', slug: 'led-fog-lights', name: 'LED fog light pair', description: 'A compact lighting upgrade for shop pickup.', isLighting: true };
const cart = { version: 2, selectedVehicleId: 'vehicle-1', items: [{ item: { id: 'item-1', variantId: variant.id, quantity: 1 }, variant, product, inventory: { availableQuantity: 8 } }] };
const order = { id: 'order-1', orderReference: 'ACC-260803-ABC123', status: 'ready_for_pickup', paymentMethod: 'pay_at_shop', paymentStatus: 'pending', currencyCode: 'PHP', totalCents: 189900, createdAt: new Date().toISOString() };

export default { title: 'Mobile/Accessories/Flows' };

export const Catalog = { render: () => <AccessoriesCatalogView accessToken="fixture" categories={[{ id: 'cat-1', name: 'Lighting' }]} products={[{ product, category: { name: 'Lighting' }, startingPriceCents: 189900 }]} status="ready" error="" search="" selectedCategoryId="" cartCount={1} hasMore={false} loadingMore={false} refreshing={false} onSearchChange={noop} onSelectCategory={noop} onProductPress={noop} onCartPress={noop} onOrdersPress={noop} onRetry={noop} onRefresh={noop} onLoadMore={noop} /> };
export const ProductWithUnverifiedFitment = { render: () => <AccessoryProductView productDetail={{ product, category: { name: 'Lighting' }, variants: [{ variant, inventory: { availableQuantity: 8 } }], media: [] }} selectedVariantId={variant.id} selectedVehicleId="vehicle-1" vehicles={[{ id: 'vehicle-1', displayName: '2019 Toyota Vios', plateNumber: 'QAJO1001' }]} fitment={{ status: 'unverified' }} fitmentLoading={false} fitmentError="" busy={false} message="" error="" onBack={noop} onSelectVariant={noop} onSelectVehicle={noop} onRetryFitment={noop} onAddToCart={noop} onOpenCart={noop} /> };
export const CatalogOnlyProduct = { render: () => <AccessoryProductView productDetail={{ product, category: { name: 'Lighting' }, variants: [{ variant, inventory: { availableQuantity: 8 } }], media: [] }} orderingEnabled={false} selectedVariantId={variant.id} selectedVehicleId="vehicle-1" vehicles={[{ id: 'vehicle-1', displayName: '2019 Toyota Vios', plateNumber: 'QAJO1001' }]} fitment={{ status: 'compatible' }} fitmentLoading={false} fitmentError="" busy={false} message="" error="" onBack={noop} onSelectVariant={noop} onSelectVehicle={noop} onRetryFitment={noop} onAddToCart={noop} onOpenCart={noop} /> };
export const CompatibilityUnavailable = { render: () => <AccessoryProductView productDetail={{ product, category: { name: 'Lighting' }, variants: [{ variant, inventory: { availableQuantity: 8 } }], media: [] }} selectedVariantId={variant.id} selectedVehicleId="vehicle-1" vehicles={[{ id: 'vehicle-1', displayName: '2019 Toyota Vios', plateNumber: 'QAJO1001' }]} fitment={null} fitmentLoading={false} fitmentError="Compatibility could not be checked. Try again before adding this item." busy={false} message="" error="" onBack={noop} onSelectVariant={noop} onSelectVehicle={noop} onRetryFitment={noop} onAddToCart={noop} onOpenCart={noop} /> };
export const Cart = { render: () => <AccessoryCartView cart={cart} busyVariantId="" error="" onBack={noop} onQuantity={noop} onRemove={noop} onRefresh={noop} onCheckout={noop} /> };
export const CatalogOnlyCart = { render: () => <AccessoryCartView cart={cart} orderingEnabled={false} busyVariantId="" error="" onBack={noop} onQuantity={noop} onRemove={noop} onRefresh={noop} onCheckout={noop} /> };
export const CartConflict = { render: () => <AccessoryCartView cart={cart} busyVariantId="" error="Your cart changed in another request. The latest quantities are shown below; review them before continuing." onBack={noop} onQuantity={noop} onRemove={noop} onRefresh={noop} onCheckout={noop} /> };
export const Checkout = { render: () => <AccessoryCheckoutView cart={cart} preview={{ totalCents: 189900 }} previewStatus="ready" previewError="" fitments={[{ variantId: variant.id, status: 'unverified' }]} contact={{ name: 'Queue Customer', phone: '09171234567', email: 'customer@example.com' }} contactErrors={{}} paymentMethod="pay_at_shop" acknowledgements={[variant.id]} busy={false} error="" onBack={noop} onContactChange={noop} onPaymentMethod={noop} onAcknowledgement={noop} onRetryPreview={noop} onSubmit={noop} /> };
export const CheckoutPriceCheckFailed = { render: () => <AccessoryCheckoutView cart={cart} preview={null} previewStatus="error" previewError="Current price and stock could not be verified. Try the check again before placing your order." fitments={[{ variantId: variant.id, status: 'universal' }]} contact={{ name: 'Queue Customer', phone: '09171234567', email: 'customer@example.com' }} contactErrors={{}} paymentMethod="pay_at_shop" acknowledgements={[]} busy={false} error="" onBack={noop} onContactChange={noop} onPaymentMethod={noop} onAcknowledgement={noop} onRetryPreview={noop} onSubmit={noop} /> };
export const OrderHistory = { render: () => <AccessoryOrdersView orders={[order]} status="ready" error="" loadingMore={false} hasMore={false} onBack={noop} onRetry={noop} onOpen={noop} onLoadMore={noop} /> };
export const ReadyForPickup = { render: () => <AccessoryOrderDetailView detail={{ order, items: [{ id: 'line-1', productName: product.name, variantName: variant.name, quantity: 1, unitPriceCents: variant.priceCents, fitment: { status: 'unverified', acknowledgedUnverified: true } }], history: [{ id: 'history-1', nextStatus: 'ready_for_pickup', reason: 'Your order is ready at the shop.', createdAt: new Date().toISOString() }], refunds: [] }} pickupCode="482901" cancelReason="" busyAction="" error="" message="" onBack={noop} onCancelReason={noop} onCancel={noop} onRetryPayment={noop} onRegenerate={noop} /> };
export const PaymentExceptionRefund = { render: () => <AccessoryOrderDetailView detail={{ order: { ...order, status: 'payment_exception', paymentMethod: 'paymongo', paymentStatus: 'exception' }, items: [], history: [], refunds: [{ id: 'refund-1', status: 'processing', amountCents: 189900, reason: 'Automatic full refund after reservation expiry.' }] }} pickupCode="" cancelReason="" busyAction="" error="" message="" onBack={noop} onCancelReason={noop} onCancel={noop} onRetryPayment={noop} onRegenerate={noop} /> };
